# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
script:
- xctool -project MPPlotExample/MPPlotExample.xcodeproj -scheme MPPlotExample -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
